server:
  port: 8070
spring:
  profiles:
    active: dev
    include: secret
  datasource:
    url: jdbc:mysql://localhost:3307/surl_dev?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: koreait123414
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1--
        format_sql: true
        highlight_sql: ture
        use_sql_comments: true
custom:
  site:
    name: "MyDefaultSite"

logging:
  level:
    com.koreait.short_url_project_02: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE